# Generated by Django 3.0.1 on 2020-10-07 22:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('auction', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('category', models.CharField(default=None, max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxIPEA8PERIQEA8QEBAQEA8PDRAQDxAPFhEWGBURFRUYHSggGRoxHRMYIT0hJikrMC4uFx8zOjMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAgIDAQAAAAAAAAAAAAAAAQcECAMFBgL/xABGEAACAgIAAwUDBgkJCQEAAAAAAQIDBBEFEiEGBxMxQSJRYQgUMlJxoTM1QnJzgZGSsiMlQ1NilKKxsxYXJFV0gqPB0RX/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AvEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACHIMqfvq7fSw4LBxJuGXYoztth0dFXok/Sb1+pfagLYTJKa+T/x/KzLOILJyLshVwx+RXWyny7lZvW/LyX7C5QBGzru0PGqcDHsyr5ctVa235ylLyjCK9ZN9NGvnaPvi4jl2OOK1iVOWq4VQVmRJN9FKUt+18IpfrA2U5gmat2dsOP4q8a23Prhte1kY78J7fk+eOv1Fkd2/e988thh50a6r7Hy1X17jVbP0hKO3yyfv8n8NoC3QRF9CQBGyTxXej20jwnFbhqWZfuGNW/R69q1r6q/zaQHtNkmu/c12pzsritVORl5F1TqubrsvnKG1HaemzYdASAAAAAAAAAAAAAAAAAAABjcQzIUVzuslGFVcJTnOTSUYxW2wOh7f9rq+FYc8iWpWy9jHqb62Xen/AGrzb9y97RrdZwbJzMTO41fOTiroR55ed99k48yXT6KT/wAl6dO+z8nI7V8YhXXzRx4uUa9rccfET9q2X9uXx9XFeSLK73OF1YfZ2eNTHkqpljQgvXStj1b9X5vfxA8x8mj8JxP8zF/itL2ZRPyaPwnE/wAzF/itL3A14+UH2gduZVgRf8niwVliT877Ftb+yGv32e77k+x1eJhU5s4Rll5cFb4j6uvHkt1wh7trUn9vwRR/bG55nGM3r+Fzp1J9Poq3w4/ckbb4tCrhCEVpQhGCS8kopJL7gPqytSTjJKUWtOMknFr1TXqavd8HZiHC+IJUR5MfIgr6ox3quXM1OEX6JNbXu5kbSFM/KRxE8bAu17UL7Kt/CdfNr/x/cB77u24++I8NxMmXW1xdd36WuTi3+vSl+s9QVB8nDKcsLMpf9HlRkvgp1rp+2D/aW9J6AwOO8Wpwse7JvlyVUx5pPpt+6KXq29JL1bNabVk9pM3MzJ+xTRRZbJ63GjHhGTqoj75N7/bJned6vay3jObXwzC5rKK7vDioeWTk7057+pHrp+XnLy0Wfw/srXwngmVjw1Kz5rfZfb/WXOlpy/N6JJe5faBTXcP+Oaf0N/8AAbQGr/cP+Oaf0N/8BtAAAAAAAAAAAAAAAAAAAAENlB99fbSWZeuEYjc4QsUcjw/ad2TzJRoXvSl5r1l9hdfaa6VeFm2QbjOGLkTjJecZKqTTXx2jUbgHGbsHIhl1KMr4czjK6rxUpNNOen+V1fUDZXus7GR4TiJTUXl3qM8ma9Hr2aU/qx3r4vb9TD79/wASZH6TH/1olUf76OL+/H/ui/8Ap1fabvK4hxHHli5Lq8GcoSahRyS3GSa6794Htvk0fheJ/mYv8Vpe5qF2P7ZZfCXdLEdadygrOerxPo8zWvd9Jl69zfbHL4tXmSy3BumdUYeHV4fSUZN79/kgKGrX87rm/wCZLm/vXU3BNQ+2NLw+MZvT8FnTtS9eV2+JH7mjbfFvVkIWRacZwjNNeTUltP7wOUqX5R/4uxPf89j/AKFpbTKW+UlmpU4GPv2pW23a/sxgo7/xgR8mvap4k/TxMf8AgsO177e3XzSj/wDPolrKyIPxZxl1ox3pP7JS6r4Lb9x8/J4wHXw261r8PlTcX74whGK+/mKW7VZc3xXOtn/KyjnXvVydkZKFzUYSXrHUUteWloC4+43sN82qXEsiOsi+H/DRkutNDX0/zpL/AA/ayxe1q/m/O/6XI/05Gvse+fiyWk8dJdFrES/9nFm973Fb6rKZyo5LYSrmlipezKLT676dGBHcP+Oaf0N/8BtAaZ9luPX8OyI5WM4q2MZRXPDnjyyWn0Ln7pu8XP4nxB42S6nUsey1KFHhvnjKCXXfl7TAuUAAAAAAAAAAAAAAAAAAQ1vocax4fVj+6jlAHF83h9WP7qPAd+dMVwXJajFPxMfqopf00SxDzPeJ2bs4pgW4dc4VzsnVJTs5uVclik/Jb9AKt+TZBSs4ntJ6hjeaT/KtL0VUY70kvfpJFfd1Hd9dwWeXK66m35xGpR8JTXLyOe98y/tfcWKBr58oPs268mriMYvwsiKqukvKN8FqLf2xX+Bnre5jt3TfiU4F9kK8nHiqqlOXKrqV0hyt/lJdNfBMsjjXCqs2mzGvgrKbVyzg/X1TT9Gmk0/RpFEdpe47LrnKWFZXkUvrGFs/Dvivc+nLL7dr7AL34rxanErd2RbXTXFdZ2S5V9i97+CNYe8LtDPjnElKiEnD2MbEq1qc05dJNejcpN/Ba9xk4Xc9xeyXLKiulfWtya+X7fYcn9xb3d13XVcKksiyayM3lcVNJqqlPzVafVv05n1+zbA9Z2Q4HHh+Di4cevg16k15Ssbcpy/ekztPm0Pqxb9W4rbOSK6EgcXzaH1IfuROs7TUQWFmNRitY17+iv6uR3Bh8XxHfRfTFpStpsrTe9Jyi0m/2ga1dxME+M0ppNeDf5rf5Bs7CiK6qKT+EUipu7runyeF59eZZkUWQjCyDhWrOb2o6TW1otxASAAAAAAAAAAI2NkACdjZAAnY2QAMPjeVKnGyboa56qLrI7W1zRrk1te7aPNZN+dTgvO+eVzcMZZMqrsOuFUkq+eVfPFpx31W+um10fkei7QVueJlxinKUsa+MYxW5NuqSSS9WdTwbsniqjH56E5xqpbja7JpTUF5wk2tp/5Ac9vauqGuaORKUaq7blRiX3qhSipctjhF6lrry+euujny+0VNfhpOy6VtauhDGosyJulrpa1Wm1D0Tfm+i69Dz+dbZ84zarPn0XKaWNVhY0oU31umOp2ZMYNKbkpJ8048qjH4N43ZJWYccadlF8oz4Zw/Gm4UyldTfj+JCVc6l7XI3Pakk10l9rD0ke1eK6nfGx2Q8Z48Y102TtnkKPM6YVpc0p6T2kumnvyZm8K4vXk86hzxnW1Gyq2qdVtbflzQmk9NLafk/TZ4Wmm2beU4ZFMauKZjthiqNmRXCyiKVnKlLne0k1FN+29b0ei7MU82RkZCWXKEq6aY35m652uMptqNLrhKMVz/AEn9LmelpbYdrxjjlWLKqFkpeJdz+DXCqdtlrgk5RhGCbb1Levcn7mcFPaTHlVddKU6o0TVdsLqbK7oWS0oQ8OS5m3zx1pPm5lrez54pjyln8PsUG4115vNPl2oOUauXb9G9P7zp+LYNvznIvjVOyNWRw6/kS140IQnGxQ39KUebm174pe4Dt6O01M+dcuTCyFfiuizCyIZE61r2q6nHmsXtJPlT03p6ZPZHjjz8PHynCVc7aq5TjKm2uKm4KT8PnXtQ69JLafvMOrJ+eZmLbXXdCrGhe523492O5SshGMaYRtjGUl15m9aTil5+XN2Bbjw3DpnC2uzHx6se2FtU65K2utRklzJc0d/lLafowMHhfa1Ttz7LpW1Y+NbGquFuBfTtuNevblHc7XOTShFb049Oqb7WntNRJW83jUypplfOGRjW0WOmK3KyMZxTkl663ptJ+h0mXg3bvuVU5qnjFeW6uX2rqI48ISlWvymm+ZL1dWvMcYjLicl4FVsYV4edW7sjGuxm7L6FCFMVbGMnHrzN60nCPr5B6u7iEIRqk5aV0q4VvlfWc1uK+B1H+2OLrm5rXUpuqd6xbnj1TU3Bxst5eWOpLTbeltb1tHV2cSnkR4bTDGylKrJxZZPi41tUcdQhJSTlKKjP2lrcHJa6701uMvh9j4Fm0KufjTo4io1KD55Tnbc4+z5tvaf6wO/zu0VVNjp1dZOEVKzwMW69Uxfl4jhFqLfnrz1t+XU+Ox3F5ZuJHIcoTU7syMZ1pckqq8u2utr3+xCPU67Hy/mWRnRtqyJrIyVkU2UYt18bYumqvklKuLUJJw17Wly6e+j1k9gMeyrBrhbU6LPnGdN0vXsKedfKKWujWpLqvTQHo9jZAAnY2QAJ2NkACdggAAAAAAAAAAAA0dXxHglV1iu/larow8PxaLpUzlXttVycekopttJp6bbWjtABh8M4dXjVqqtNQXM/alKcpSk25TnOTcpSbbbbe3szNAABoABoaAAaGgAI0vcv2E6AAaAAAAAAAAAAAAAAQAJIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACGfLYH2DhcmfDmwMnY2YjkyOZgZmxsw+Zk7YGXsbMPbJ2wMvYMXmZHMwMsGJzM+otgZIOFM5EwPoEJkgAAAAAAAAToAAQCQBAJAEaIaPoAfHKHA+wBx+GPDRyADj8MeGcgA4/DQVZyAD45COQ5AB8chKifQA+eUnRIAgEgCASAIJAAgEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/9k=', upload_to='uploads/', verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
