# Generated by Django 3.0.1 on 2020-10-11 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 22, 45, 192558, tzinfo=utc)),
        ),
    ]
