# Generated by Django 3.0.1 on 2020-10-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201013_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(default='avatars/avatar.png', upload_to='avatars/', verbose_name='image'),
        ),
    ]
