# Generated by Django 3.0.1 on 2020-10-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlistings_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatars/avatar.png', upload_to='avatars/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='user',
            name='image2',
            field=models.FilePathField(default='avatars/avatar.png', verbose_name='image'),
        ),
    ]
