# Generated by Django 3.0.1 on 2020-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201017_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='static/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image2',
            field=models.FilePathField(default='images/no_image.jpg', verbose_name='image'),
        ),
    ]
